package com.example.dyy.fmcw;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.app.Activity;
import android.util.Log;
import android.view.View;

public class MainActivity extends AppCompatActivity {

    private PlayThread mPlayThread;
    private Record recordThread;

    short[] recorddata;

    //keep this cause we need it later for two channel generating two f signals
//    private PlayThread mChannelLeftPlayer;
//    private PlayThread mChannelRightPlayer;


    //generated by system , initialize interface of app
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    //play finction is connected to the play button on interfeace
    public void play(View button){
        Log.e("Play","playpaly");
        if (null != mPlayThread) {
            mPlayThread.stopp();
            mPlayThread = null;
        }
        mPlayThread = new PlayThread(this);
        mPlayThread.start();
     //   mPlayThread.play();

    }


   //stop function connested to stop button on interface (pause function)
    public void stop(View button){
        Log.e("stop","stopstop");
        if (null != mPlayThread) {
            mPlayThread.pause();

        }
    }

    //record function related to button record
    public void record(View button){
        Log.e("record","recordrecord");
        recordThread = new Record();
        recordThread.start();
        recorddata=recordThread.getRecord();

    }

    //play function connected to button play, plan to display record data ,haven't finished yet
    public void playRecord(View button){
        PlayRecord playRecord=new PlayRecord(recorddata);
        playRecord.start();

    }


}
